Создайте массив 10х10, заполненный в центре нулями, а по границе единицами

In [6]:
import numpy as np
z = np.pad(np.zeros((8,8)),((1,1),(1,1)), 'constant', constant_values = (1))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Создайте массив 8х8, заполненный 0 и 1 в шахматном порядке

In [18]:
n = (np.arange(8) + np.arange(8).reshape((8,-1))) % 2
print(n)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Создайте матрицу 5x5 со значениями 1,2,3,4 под главной диагональю. Остальные значения - нули

In [26]:
z = np.diag([1,2,3,4], -1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Создайте случайный массив 5х5 и нормируйте его так, чтобы среднее вдоль каждой строки было равно нулю.

In [38]:
z = np.random.randint(1,10,(5,5)) - np.mean(z,1).reshape((5,-1))
print(z)

[[-4.2  1.8  1.8 -2.2 -2.2]
 [-3.8 -1.8  2.2 -0.8  3.2]
 [ 0.8 -3.2 -2.2 -2.2  3.8]
 [ 1.2 -0.8  3.2  6.2 -0.8]
 [-1.6 -2.6  0.4  0.4  5.4]]


Создайте двумерный массив 10x3, заполненный случайными числами от 0 до 1. В каждой строке выберите значение, наиболее близкое к 0.5

In [68]:
z = np.random.random((10,3))
print(z)
z[np.arange(10),np.abs(z - 0.5).argmin(1)]

[[0.70942885 0.37251323 0.45580341]
 [0.82364164 0.84492843 0.96583622]
 [0.13184658 0.09582266 0.46595827]
 [0.75712952 0.5737034  0.53179069]
 [0.80187531 0.99813822 0.35504123]
 [0.69053524 0.44393108 0.35311806]
 [0.5373022  0.24368048 0.51053753]
 [0.05266368 0.85278334 0.07967136]
 [0.15328481 0.49891607 0.19177413]
 [0.92309904 0.56260415 0.29745139]]


array([0.45580341, 0.82364164, 0.46595827, 0.53179069, 0.35504123,
       0.44393108, 0.51053753, 0.85278334, 0.49891607, 0.56260415])

Создайте двумерный массив 6x6, заполненный случайными значениями. Сумму по каждой строке поделите на максимальный элемент из столбца с тем же индексом

In [54]:
arr = np.random.rand(0, 100, size = (6,6))
print(arr)
print(np.sum(arr, axis = 1) / np.max(arr, axis = 0)) 

[[73 32 82 95 90 81]
 [44 18 78 46  2 24]
 [29 24 38  7 15 47]
 [27 13 22 39 50 55]
 [28 94 94 34 68 46]
 [51 57 54 82 20 69]]
[6.20547945 2.25531915 1.70212766 2.16842105 4.04444444 4.11111111]


На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль

In [89]:
z = np.array([0,1,2,1,7,3,0])
cond = np.zeros_like(z, dtype = bool)
cond[1:] = (z[:-1] == 0)
np.max(z, where = cond, initial = 0)
where=np.insert(z[:-1] == 0, 0, False)
print(where)

[False  True False False False False False]


Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [114]:
x = np.ones(10)
i = np.array([0,1,2,3,3,5,3,5,4])
x = x + np.bincount(i, minlength = x.shape[0])
print(x)

[2. 2. 2. 4. 2. 3. 1. 1. 1. 1.]


Задайте два массива a = np.array([[1, 4.9, 2.4], [7.1, 7, 9.8], [2, 4.6, 1.2]]) и b = np.array([3, 5, 10, 0]). Создайте массив, в котором каждый элемент первого массива заменен на ближайший к нему элемент второго массива.

In [38]:
a = np.array([[1, 4.9, 2.4], [7.1, 7, 9.8], [2, 4.6, 1.2]])
b = np.array([0,3,5])
res = b[np.abs(np.stack([a] * b.shape[0]) - b.reshape((b.shape[0],1,1))).argmin(axis = 0)]
print(res)

[[0 5 3]
 [5 5 5]
 [3 5 0]]
[[0 5 3]
 [5 5 5]
 [3 5 0]]


Найдите скользящие средние с окном размера 3 по массиву a = np.array([1, 4.9, 2.4, 7.1, 7, 9.8, 2, -5, 4.6, 1.2])

In [45]:
arr = np.array([1,2,3,4,5,6,7,8])
window = 3
result = [int(np.sum(arr[i:i+window]) / window) for i in range(arr.shape[0] - window + 1)]
print(result)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[2, 3, 4, 5, 6, 7]
